ranked = [
    ["safer", "production-ready"],
    ["tdir", "production-ready"],
    ["editor", "production-ready"],
    ["psplit", "production-ready"],
    ["gitz", "production-ready"],
    ["pullman", "beta"],
    ["nc", "production-ready"],
    ["dtyper", "production-ready"],
    ["clsprop", "production-ready"],
    ["threa", "production-ready"],
    ["sproc", "production-ready"],
    ["fil", "beta"],
    ["xmod", "production-ready"],
    ["impall", "production-ready"],
    ["nmr", "experimental"],
    ["datacls", "production-ready"],
    ["abbrev", "production-ready"],
    ["dek", "production-ready"],
    ["recs", "experimental"],
    ["wavemap", "mothballed"],
    ["vl8", "experimental"],
    ["litoid", "experimental"],
    ["fortune", "personal"],
    ["plur", "beta"],
    ["def_main", "experimental"],
    ["multi", "personal"],
    ["blocks", "personal"],
    ["hardback", "experimental"],
    ["loady", "mothballed"],
    ["runs", "mothballed"],
    ["cfgs", "beta"],
    ["backer", "experimental"],
    ["test", "personal"],
    ["dotfiles", "personal"],
]

new-unranked = [
    "tuney",
    "zoialib",
    "fixo",
]

[api_documentation]
clsprop = false
dek = false
datacls = false
impall = false

[api_paths]
nc = ["nc", "nc.color", "nc.colors"]
fil = ["fil.read", "fil.write"]
